[project]
name = "ch12"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Michaël CHLON", email = "mic.a.elle.chlon@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.14.3",
    "beautifulsoup4>=4.15.0",
    "chromadb>=1.5.9",
    "fastmcp>=4.0.4",
    "html2text>=2025.4.15",
    "langchain>=1.4.0",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-mcp-adapters>=0.3.1",
    "langchain-openai>=1.6.2",
    "langgraph>=1.2.11",
    "langgraph-supervisor>=0.0.31",
    "lxml>=6.1.3",
    "python-dotenv>=1.2.3",
    "tiktoken>=0.14.0",
]

[project.scripts]
ch12 = "ch12:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
  "jupyterlab-lsp>=5.3.0",
  "jupyterlab-wakatime>=0.2.0",
  "python-lsp-server[all]>=1.15.0",
  "ruff>=0.16.3",
]
